gamegen/gamegen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from rest_framework import serializers, generics, permissions
from modelclasses import models

from home.views import filterGames

class LocationSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.location
        fields = ('name', 'id', 'disliker',)
class GenreSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.genre
        fields = ('name', 'id',)
class TeamingSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.teaming
        fields = ('name', 'id',)
class GameSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.game
        fields = ('name', 'genre', 'teaming', 'duration', 'min_player', 'max_player',)


class LocationList(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated]
    def get_queryset(self):
        if self.request.user.is_superuser:
            queryset = models.location.objects.all()
        else:
            queryset = self.request.user.creater.all()|self.request.user.editer.all()|self.request.user.viewer.all()
        return queryset
    serializer_class = LocationSerializer

class GenreList(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated]
    queryset = models.genre.objects.all()
    serializer_class = GenreSerializer

class TeamingList(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated]
    queryset = models.teaming.objects.all()
    serializer_class = TeamingSerializer

class GameList(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated]
    def get_queryset(self):
        gameData = filterGames(self.request)
        games = gameData["games"]
        if games.model is models.dislikes:
            allGames = []
            for game in games:
                allGames.append(game.game.id)
            games = models.game.objects.filter(id__in=allGames)
        return games
    serializer_class = GameSerializer






urlpatterns = [
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('modelclasses/', include('modelclasses.urls')),
    path('', include('home.urls')),
    # path('htmx/', views.htmx_home, name='htmx'),
    path('admin/', admin.site.urls),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('api/location/', LocationList.as_view()),
    path('api/genre/', GenreList.as_view()),
    path('api/teaming/', TeamingList.as_view()),
    path('api/games/', GameList.as_view()),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamegen/home/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views
# from . import htmx


router = routers.DefaultRouter()

urlpatterns = (
    path("api/v1/", include(router.urls)),
    path('', views.HomeView.as_view(), name="HomeView"),
    path('gameTable/', views.gameTable, name="GameTable"),
    path('createGame/', views.CreateGameView.as_view(), name="CreateGameView"),
    path('addDislikes/', views.addDislikes, name="AddDislikes"),
    path('getBGG/', views.loadFromBGG, name="getBGGData"),
    path('saveNewGame/', views.saveNewGame, name="saveNewGame"),
    path('addGame/', views.addGame, name="addGame"),
    path('createExpansion/', views.CreateExpansionView.as_view(), name="CreateExpansionView"),
    path('addWishlist/', views.addWishlist, name="addWishlist"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('changeDislikes', views.changeDislikes, name="changeDislikes"),
    path('changeDislikesSave', views.changeDislikesSave, name="changeDislikesSave"),
    path('addToStorage', views.addToStorage, name="addToStorage"),
    path('deleteElement', views.deleteItem, name="deleteElement"),
    path('settings/', views.UserSettings.as_view(), name="UserSettings"),
)

gamegen/home/models.py
from django.db import models
from django.urls import reverse
# No models in this app

gamegen/modelclasses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from multiselectfield import MultiSelectField



class teaming(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return str(self.name)

class dislikes(models.Model):

    # Relationships
    game = models.ForeignKey("modelclasses.game", on_delete=models.CASCADE)
    location = models.ForeignKey("modelclasses.location", on_delete=models.CASCADE)

    # Fields
    disliker = models.TextField(max_length=200,null=True, blank=True)

    class Meta:
        pass

    def __str__(self):
        return str(self.game.name + " - " + self.location.name)

    def get_absolute_url(self):
        return reverse("modelclasses_dislikes_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("modelclasses_dislikes_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("modelclasses_dislikes_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("modelclasses_dislikes_htmx_delete", args=(self.pk,))


class expansion(models.Model):
    name = models.CharField(max_length=60)
    # Relationships
    base_game = models.ForeignKey("modelclasses.game", on_delete=models.CASCADE)
    number = models.IntegerField()
    genre = models.ManyToManyField("modelclasses.genre", blank=True)
    teaming = models.ManyToManyField("modelclasses.teaming", blank=True)
    duration = models.IntegerField()
    min_player = models.IntegerField()
    max_player = models.IntegerField()
    # Fields
    release_date = models.DateField(null=True, blank=True)
    rule_link = models.URLField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    class Meta:
        pass

    def __str__(self):
        return str(self.name+" - "+self.base_game.name)

    def get_absolute_url(self):
        return reverse("modelclasses_expansion_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("modelclasses_expansion_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("modelclasses_expansion_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("modelclasses_expansion_htmx_delete", args=(self.pk,))


class game(models.Model):
    name = models.CharField(max_length=50)
    # Relationships
    genre = models.ManyToManyField("modelclasses.genre", blank=True)
    teaming = models.ManyToManyField("modelclasses.teaming", blank=True)
    duration = models.IntegerField()
    # Fields
    min_player = models.IntegerField()
    max_player = models.IntegerField()
    release_date = models.DateField(null=True, blank=True)
    rule_link = models.URLField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    class Meta:
        pass

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("modelclasses_game_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("modelclasses_game_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("modelclasses_game_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("modelclasses_game_htmx_delete", args=(self.pk,))


class genre(models.Model):

    # Fields
    name = models.CharField(max_length=60)

    class Meta:
        pass

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("modelclasses_genre_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("modelclasses_genre_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("modelclasses_genre_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("modelclasses_genre_htmx_delete", args=(self.pk,))


class location(models.Model):
    name = models.CharField(max_length=60)
    creater = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, related_name="creater")
    editer = models.ManyToManyField("auth.User", related_name="editer", blank=True)
    viewer = models.ManyToManyField("auth.User", related_name="viewer", blank=True)
    # Relationships
    game = models.ManyToManyField("modelclasses.game", through='dislikes', blank=True)
    expansions = models.ManyToManyField("modelclasses.expansion", related_name="expansions", blank=True)

    wishlist_games = models.ManyToManyField("modelclasses.game", related_name="wishlist_games", blank=True)
    wishlist_expansions = models.ManyToManyField("modelclasses.expansion", related_name="wishlist_expansions", blank=True)
    
    disliker = models.TextField(max_length=200,null=True, blank=True)
    

    # Fields


    class Meta:
        pass

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("modelclasses_location_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("modelclasses_location_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("modelclasses_location_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("modelclasses_location_htmx_delete", args=(self.pk,))

class UserSettings(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    home = models.ForeignKey("modelclasses.location", on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return str(self.user.username + " - " + self.home.name)
    

gamegen/home/forms.py
from django import forms
from . import models

gamegen/templates/home/add_dislike.html
{% load i18n %}

<label for="dislikes" class="form-label">{% trans 'Dislikes' %}</label>
<select id="dislikes" class="select select-dislike select2" multiple style="width:10vw" name="dislike">
    {% for dislike in dislikes %}
    <option value="{{dislike}}">{{dislike}}</option>
    {% endfor %}
</select>

<script>
    $(document).ready(function() {
      $('.select-dislike').select2({tags: true});
    });
</script>

gamegen/templates/home/add_game.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}
<form id="addGameToLocation" hx-get="{% url 'addGame' %}" hx-trigger="submit">
  <label for="select-game" class="form-label">{% if type == "expansion" %}{% trans 'ExpansionName' %}{% else %}{% trans 'GameName' %}{% endif %}</label>
  <div class="input-group mb-3">
      <select required id="select-game" class="form-select" style="width:10vw" name="game" multiple data-placeholder="Choose one game">
          <option value="">{% translate "" %}</option>
          {% for game in games %}
          <option value="{{game.id}}">{{game}}</option>
          {% endfor %}
      </select>
      <button class="btn btn-outline-secondary" type="button" id="button-addon2" data-bs-toggle="modal" data-bs-target="#gameModal">+</button>
  </div>
  </br>

  <label for="location" class="form-label">{% trans 'Location' %}</label>
  <select id="location" required class="select select-location select2" style="width:10vw" name="location" {% if type != "expansion" %}hx-get="{% url 'AddDislikes' %}" hx-target="#dislikerDiv" hx-trigger="change" {% endif %}>
      <option value=""></option>
      {% for location in locations %}
      <option value="{{location.id}}">{{location.name}}</option>
      {% endfor %}
  </select>
  {% if type == "expansion" %}
  <input type="hidden" name="type" value="expansion">
  </br>
  {% else %}
  <div id="dislikerDiv">

  </div>
  {% endif %}

  <button type="submit" class="btn btn-primary">{% if type == "expansion" %}{% trans "Save Expansion" %}{% else %}{% trans "Save Game" %}{% endif %}</button>
  <button type="submit" class="btn btn-primary" formaction="{% url 'addWishlist' %}">{% trans "Add to Wishlist" %}</button>
</form>

<div class="overviewTable">

</div>




  <!-- Modal -->
  <div class="modal fade" id="gameModal" tabindex="-1" aria-labelledby="gameModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="gameModalLabel">{% if type == "expansion" %}{% translate "New Expansion" %}{% else %}{% translate "New Game" %}{% endif %}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <h3>{% translate "Import from BGG" %}</h3>
            <form hx-get="{% url 'getBGGData' %}" hx-target="#game_data">
              <div class="input-group mb-3">
                  <input type="text" id="InputBGGId" class="form-control" name="id" placeholder="BGG Game ID">
                  <button class="btn btn-outline-secondary" type="submit" id="button-addon2">{% translate "Get Data" %}</button>
              </div>
              {% if type == "expansion" %}<input type="hidden" name="type" value="expansion">{% endif %}
            </form>
            <hr>
            <h3>{% translate "Game Data" %}</h3>
            <div id="game_data">
                {% include "home/game_data_htmx.html" %}
            </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" form="newGameForm" class="btn btn-primary">Save Game</button>
        </div>
      </div>
    </div>
  </div>



<script>

    window.addEventListener("DOMContentLoaded", (e) => {
        $('select').on('select2:select', function (e) {
            $(this).closest('select').get(0).dispatchEvent(new Event('change'));
        });

    });
    $( '#select-game' ).select2( {
        theme: "bootstrap-5",
        width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
        placeholder: $( this ).data( 'placeholder' ),
    } );   

    //https://boardgamegeek.com/xmlapi2/thing/?id=355326 -> Zeigt auf Heroes of Might and Magic
</script>


{% endblock content %}

gamegen/templates/home/change_dislike.html
{% load i18n %}
<form id="dislikeForm" hx-get="{% url 'changeDislikesSave' %}" hx-include="[name='location'], [name='genre'], [name='teaming'],[name='duration'],[name='min-player'],[name='type']" hx-target="#game-table">
  <h3>{{game.name}}</h3>
  <input id="game" type="hidden" name="game" value="{{game.id}}">
  <input id="location" type="hidden" name="location" value="{{location.id}}">
  <label for="dislikes" class="form-label">{% trans 'Dislikes' %}</label>
  <select id="dislikes" class="select select-dislike select2" multiple style="width:10vw" name="dislike">
      {% for dislike in dislikes %}
      <option value="{{dislike}}" {% if dislike in dislikeList %}selected{% endif %}>{{dislike}}</option>
      {% endfor %}
  </select>
</form>

<script>
    $(document).ready(function() {
      $('.select-dislike').select2({tags: true, dropdownParent: $('#changeDislikes')});
    });
</script>

gamegen/templates/home/game_data_htmx.html
{% load i18n %}

<form id="newGameForm" name="newGameForm" hx-post="{% url 'saveNewGame' %}" hx-trigger="submit" hx-encoding="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="name" class="form-label">{% translate "Name" %}</label>
        <input type="text" class="form-control" id="name" name="name" value="{{data.name}}" required>
    </div>
    {% if type == "expansion" %}
    <div class="mb-3">
        <label for="baseGame" class="form-label">{% translate "Basegame" %}</label>
        <select class="select-control select-modal select2" id="baseGame" name="baseGame" required style="width:100%">
            <option value="">{% translate "Unset" %}</option>
            {% for game in allGames %}
            <option value="{{game.id}}">{{game.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="number" class="form-label">{% translate "Number" %}</label>
        <input type="number" class="form-control" id="number" name="number" value="" required>
    </div>
    <input type="hidden" name="type" value="expansion">
    {% endif %}
    <div class="mb-3">
        <label for="duration" class="form-label">{% translate "Duration" %}</label>
        <input type="number" class="form-control" id="duration" name="duration" value={{data.duration}} required>
    </div>
    <div class="mb-3">
        <label for="minPlayer" class="form-label">{% translate "min Player" %}</label>
        <input type="number" class="form-control" id="minPlayer" name="minPlayer" value={{data.minPlayer}} required>
    </div>
    <div class="mb-3">
        <label for="maxPlayer" class="form-label">{% translate "max Player" %}</label>
        <input type="number" class="form-control" id="maxPlayer" name="maxPlayer" value={{data.maxPlayer}} required>
    </div>
    <div class="mb-3">
        <label for="releaseDate" class="form-label">{% translate "Release Date" %}</label>
        <input type="date" class="form-control" name="releaseDate" id="releaseDate">
    </div>
    <div class="mb-3">
        <label for="ruleLink" class="form-label">{% translate "Rule Link" %}</label>
        <input type="url" class="form-control" name="ruleLink" id="ruleLink">
    </div>
    <div class="mb-3">
        <label for="ruleFile" class="form-label">{% translate "Rule File" %}</label>
        <input type="file" class="form-control" name="ruleFile" id="ruleFile">
    </div>
    <div class="mb-3">
        <label for="genre" class="form-label">{% translate "Genre" %}</label>
        <select class="select-control select-dropdowns select2" multiple id="genre" name="genre" style="width:100%">
            {% for genre in genres %}
            <option value="{{genre.id}}">{{genre.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="teaming" class="form-label">{% translate "Teaming" %}</label>
        <select class="select-control select-dropdowns select2" multiple id="teaming" name="teaming" style="width:100%">
            {% for teaming in teamings %}
            <option value="{{teaming.id}}">{{teaming.name}}</option>
            {% endfor %}
        </select>
    </div>
</form>

<script>

    $( '.select-dropdowns' ).select2( {
        theme: "bootstrap-5",
        placeholder: $( this ).data( 'placeholder' ),

    } );   
    $( '.select-modal' ).select2( {
        theme: "bootstrap-5",
        width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
        placeholder: $( this ).data( 'placeholder' ),
        dropdownParent: $('#gameModal')

    } );   
 
 
    
    document.addEventListener('htmx:afterRequest', function(evt) {
        if (evt.detail.xhr.status == 200){
            if(evt.detail.target.id=="newGameForm"){
                location.reload()
            }
            if(evt.detail.target.id=="addGameToLocation"){
                location.reload()
            }
        }
    });
</script>

gamegen/templates/home/game_table.html
{% load i18n %}

<div id="game-table" class="table table-striped">
    <table border=1 style="width:75vw" id="table_detail">
        <thead>
            <tr>
                <th style="width:25vw">
                {% trans 'Name' %}
                </th>
                <th style="width:15vw">
                {% trans 'Genre' %}
                </th>
                <th style="width:15vw">
                    {% trans 'Teaming' %}
                </th>
                <th style="width:15vw">
                {% trans 'Duration' %}
                </th>
                <th style="width:15vw">
                    {% trans 'PlayerCount' %}
                    </th>
                <th style="width:15vw">
                {% trans 'GameDislikes' %}
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr onclick="showHideRow('hidden_{{game.id}}')" class="gameRows" data-name="{{game.id}}" {% if game in notGames %}style="background-color:red"{% endif %}>
                <td> {% if type == "collection" %}{{game.game.name}}{% else %}{{game.name}} {% endif %}</td>
                <td> {% if type == "collection" %}{{game.game.genre.all|join:", "}}{% else %}{{game.genre.all|join:", "}} {% endif %}</td>
                <td> {% if type == "collection" %}{{game.game.teaming.all|join:", "}}{% else %}{{game.teaming.all|join:", "}} {% endif %}</td>
                <td> {% if type == "collection" %}{{game.game.duration}}{% else %}{{game.duration}} {% endif %} min</td>
                <td> {% if type == "collection" %}{{game.game.min_player}}{% else %} {{game.min_player}}{% endif %}  - {% if type == "collection" %}{{game.game.max_player}}{% else %} {{game.max_player}}{% endif %}</td>
                <td> {{game.disliker}}</td>
                <td style="width:1rem"> 
                    {% if type == "wishlist" %}
                        {% if location in user.editer.all or location in user.creater.all %}
                            {% if game in location.wishlist_games.all %}<a hx-get="{% url 'addToStorage' %}" hx-target="#game-table" hx-trigger="click" hx-vals='{"game": {{game.id}}, "location": {{location.id}}, "elementType": "game" }' hx-include="[name='genre'], [name='teaming'],[name='duration'],[name='min-player'],[name='type']"><i class="material-icons me-1">add_shopping_cart</i></a>{% endif %}
                            {% if game in location.wishlist_games.all %}<a hx-get="{% url 'deleteElement' %}" hx-target="#game-table" hx-trigger="click" hx-vals='{"game": {{game.id}}, "location": {{location.id}}, "type": "{{type}}","elementType": "game"}' hx-include="[name='genre'], [name='teaming'],[name='duration'],[name='min-player'],[name='type']"><i class="material-icons me-1">delete</i></a>{% endif %}
                        {% endif %}
                    {% else %}
                        {% if location in user.editer.all or location in user.creater.all %}
                            <a hx-get="{% url 'changeDislikes' %}" hx-target="#modalDislikeBody" hx-trigger="click" hx-vals='{"game": {{game.game.id}}, "location": {{location.id}}}' data-bs-toggle="modal" data-bs-target="#changeDislikes"><i class="material-icons me-1">edit</i></a>
                            <a hx-get="{% url 'deleteElement' %}" hx-target="#game-table" hx-trigger="click" hx-vals='{"game": {{game.game.id}}, "location": {{location.id}}, "type": "{{type}}","elementType": "game"}' hx-include="[name='genre'], [name='teaming'],[name='duration'],[name='min-player'],[name='type']"><i class="material-icons me-1">delete</i></a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            <tr id="hidden_{{game.id}}"  class="hidden_row">
                <td colspan="7">
                    <p>
                        <table class="table" style="font-size:small">
                            <tr class="table-info text-center">
                                <th>{% trans 'Number' %}</th>
                                <th>{% trans 'Name' %}</th>
                                <th>{% trans 'Genre' %}</th>
                                <th>{% trans 'Teaming' %}</th>
                                <th>{% trans 'Duration' %}</th>
                                <th>{% trans 'PlayerCount' %}</th>
                            </tr>
                            {% for expansion in game.expansion_set.all %}
                                {% if expansion in location.wishlist_expansions.all %}
                                <tr class="table-info text-center">
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.number}}</td>
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.name}}</td>
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.genre.all|join:", "}}</td>
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.teaming.all|join:", "}}</td>
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.duration}}min</td>
                                    <td {% if game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.min_player}}-{{expansion.max_player}}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                            {% for expansion in game.game.expansion_set.all %}
                                {% if expansion in location.expansions.all %}
                                <tr class="table-info text-center">
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.number}}</td>
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.name}}</td>
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.genre.all|join:", "}}</td>
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.teaming.all|join:", "}}</td>
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.duration}}min</td>
                                    <td {% if game.game in notGames and expansion in expansions %}style="background-color:lightgreen"{% endif %}>{{expansion.min_player}}-{{expansion.max_player}}</td>
                                </tr>
                                {% endif %}
                        {% endfor %}
                        </table>
                        <ul>

                        </ul>
                    </p>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<script>
    function showHideRow(row){
        $("#"+row).toggleClass("hidden_row");
      }
    
</script>
<style>
    .hidden_row{
        display:none
    }
</style>

gamegen/templates/home/settings.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}


<form method="POST">
    <label for="location" class="form-label">{% translate "User Settings" %}</label>
    <select id="location" class="select-normal select2" style="width:10vw" name="location" hx-get="{% url 'GameTable' %}" hx-target="#game-table" hx-trigger="change" hx-include="[name='genre'], [name='player'],[name='teaming'],[name='duration'],[name='type']">
        {% for location in locations %}
        <option value="{{location.id}}" {% if location == setting.home %}selected{% endif %}>{{location.name}}</option>
        {% endfor %}
    </select>
    {% csrf_token %}

    <input type="submit" value='{% translate "Save" %}' />
</form>

</br>



<script>

    window.addEventListener("DOMContentLoaded", (e) => {
        $('select').on('select2:select', function (e) {
            $(this).closest('select').get(0).dispatchEvent(new Event('change'));
        });
    });   
    
</script>

{% endblock content %}